# Generated by Django 3.1.5 on 2021-01-31 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210128_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=datetime.datetime(2021, 1, 31, 5, 22, 9, 712599, tzinfo=utc), upload_to='avatars'),
            preserve_default=False,
        ),
    ]
