# Generated by Django 3.1.5 on 2021-01-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210130_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['created'], 'verbose_name_plural': 'Room types'},
        ),
    ]
