# Generated by Django 3.1.5 on 2021-01-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210131_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cleanlines',
            new_name='cleanliness',
        ),
    ]
