# Generated by Django 3.1.5 on 2021-02-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210131_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cleanliness',
            new_name='cleanlines',
        ),
    ]
